
# load("//mediapipe/framework/port:build_config.bzl", "mediapipe_cc_proto_library")

package(default_visibility = ["//visibility:public"])


cc_library(
    name="landmark_to_mask_calculator",
    srcs=["landmark_to_mask_calculator.cc"],
    visibility=["//visibility:public"],
    deps=[
        "//mediapipe/framework:calculator_framework",
    ],
    alwayslink=1
)