


cc_library(
    name="first_calculator",
    srcs=["first_calculator.cc"],
    visibility=["//visibility:public"],
    deps=[
        "//mediapipe/framework:calculator_framework",
    ],
    alwayslink=1
)